### ISSUE TITLE
Consider styling `input[type=submit]` as button

### ISSUE THREAD

**Issue by czottmann** [longsien/BareCSS#3]
Normally, `input[type=submit]` is rendered as a button element by the browser.  When applying BareCSS they don't look like buttons anymore but like a BareCSS input field that can't be typed in.

Would it be possible to display those elements as BareCSS buttons as well?

**Comment by longsien** [comment]
New release (v1.1.0) will fix this issue. Will leave this open until next version is released.

**Comment by longsien** [comment]
Fixed in latest release.
