### ISSUE TITLE
nav bar with no li elements has incorrect height

### ISSUE THREAD

**Issue by thetrav** [longsien/BareCSS#4]
There are some cases where the nav bar should be displayed, but with only the site logo (pretty much logon and registration so far as I can see)

in this case the bottom line of the nav bar appears above the site logo and looks a bit derpy

**Comment by thetrav** [comment]
Current work around is:

```
<li><a>&nbsp;</a></li>
```

It's not great.  Leaves a little easter egg (also known as a bug) if someone hovers in the right spot

**Comment by longsien** [comment]
Fixed in latest release.
